name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-'
  pull_request:
    branches-ignore:
      - 'ga-ignore-'

jobs:

  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Find unwanted files
          run: var=0; for i in $(find -name "*.o" -o -name "*.a" -o -name "*.gcda" -o -name "*.gcno" -o -name "*.so" -o -name "*.gcov" -o -iname "*pain_au_chocolat*" -o -name "\#*\#" -o -name "*~" -o -path '*/tmp/*' -type f); do echo "::error file=$line,line=1::Unwanted file detected $i"; var=1; done; exit $var

  check_program_compilation:
    needs: [check_repository_cleanliness]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: try compile project
        run: make
      - name: try clean project
        run: make fclean

  run_tests:
    needs: [check_program_compilation]
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: try tests
        run: make test_run

  push_to_mirrors:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{env.MIRROR_URL}}
          ssh_private_key:
            ${{secrets.GIT_SSH_PRIVATE_KEY}}
